import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        layout: {
          unsafe_disableDevelopmentModeWarnings: true,
        },
      }}>
      <html lang="en">
        <body suppressHydrationWarning
          className="dark:bg-muted-dark dark:text-white"
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
